# SPDX-License-Identifier: GPL-3.0-or-later
# Pinned (not "stable") so CI and local dev run the *same* clippy/rustfmt and
# lints can't appear only on the runner. Keep this in sync with
# RUST_TOOLCHAIN in .github/workflows/ci.yml; bump both together (and the dev
# environment) in a dedicated change.
[toolchain]
channel = "1.95.0"
components = ["rustfmt", "clippy"]
profile = "minimal"
