#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Regenerate crates/vault-core/src/wordlist.rs from the EFF large wordlist.
#
# The word *data* is the Electronic Frontier Foundation's diceware list,
# licensed CC-BY-3.0 — see REUSE.toml and CREDITS.md. This script (Vault's
# code) is GPL-3.0-or-later; the generated wordlist.rs carries the EFF's
# CC-BY-3.0 via the REUSE.toml override. Run from the repo root:
#
#   sh crates/vault-core/tools/gen_wordlist.sh
#
set -eu

URL="https://www.eff.org/files/2016/07/18/eff_large_wordlist.txt"
OUT="crates/vault-core/src/wordlist.rs"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

curl -fsSL --max-time 60 "$URL" -o "$tmp"

# The EFF file is `<dice-roll>\t<word>`; take the word column.
{
    echo "//! EFF large diceware wordlist (7776 words) for \`generate_passphrase\`."
    echo "//!"
    echo "//! Verbatim word data from the Electronic Frontier Foundation, licensed"
    echo "//! CC-BY-3.0 (declared in \`REUSE.toml\`; credited in \`CREDITS.md\`)."
    echo "//! Generated by \`crates/vault-core/tools/gen_wordlist.sh\` — do not hand-edit."
    echo
    echo "pub const EFF_LONG: &[&str] = &["
    cut -f2 "$tmp" | sed 's/.*/    "&",/'
    echo "];"
} >"$OUT"

echo "wrote $OUT ($(grep -cE '^[[:space:]]+\"' "$OUT") words)"
